using Microsoft.ApplicationInsights.Channel;
using Microsoft.ApplicationInsights.DataContracts;
using Microsoft.ApplicationInsights.Extensibility;

namespace GrubifyApi.Telemetry;

/// <summary>
/// Telemetry processor that discards internal managed-identity (MSI) token requests
/// from Application Insights. These calls target the local MSI endpoint
/// (e.g. http://localhost:{port}/msi/token) and are auth-bootstrap traffic, not
/// customer-facing requests. Without this filter a single slow token acquisition can
/// push the average request duration above the user-latency SLO threshold and trigger
/// a false-positive alert, as described in incident ai-Zava-xnfiyr.
/// </summary>
public sealed class InternalRequestFilter : ITelemetryProcessor
{
    private readonly ITelemetryProcessor _next;

    public InternalRequestFilter(ITelemetryProcessor next)
    {
        _next = next;
    }

    public void Process(ITelemetry item)
    {
        if (item is RequestTelemetry request && IsInternalRequest(request))
        {
            // Drop the item — do not forward it to the next processor or to the
            // Application Insights ingestion endpoint.
            return;
        }

        _next.Process(item);
    }

    /// <summary>
    /// Returns <c>true</c> when the request targets a localhost MSI token endpoint
    /// or any other internal non-customer-facing path that should be excluded from
    /// user-latency telemetry.
    /// </summary>
    internal static bool IsInternalRequest(RequestTelemetry request)
    {
        var url = request.Url?.ToString() ?? string.Empty;

        // Match http(s)://localhost:<port>/msi/token requests generated by the
        // Azure Identity / MSI credential libraries during environment bring-up.
        if (url.Contains("localhost", StringComparison.OrdinalIgnoreCase) &&
            url.Contains("/msi/token", StringComparison.OrdinalIgnoreCase))
        {
            return true;
        }

        return false;
    }
}
